[tool.poetry]
name = "speechalyze"
version = "0.1.0"
description = "measure acoustic-prosodic entrainment in speech"
authors = ["Erik Ernst"]

[tool.poetry.dependencies]
python = "^3.8"
pydub = "^0.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
